Allow hiding of contest arguments and output on a case-by-case basis
engineer-man/emkc pull request #178
Opened 2022-03-28 03:37 UTC by HexF

Adds an options system for contest inputs, allowing control on a case-by-case basis to hide/show test cases and their outputs.
This system allows for easy expansion in the future if we want to add other special options to each case.

Options are specified in the inputs portion of the cases by starting the case with a `|`, the character used as a input separator:
```
|...options string...|inputs...
```
Note that options do not need to be included to allow for backwards compatibility with existing contests.

Within this options string, you can currently specify 3 options:
* `hide_input` - Hides all arguments for this test case while the contest is active
* `hide_output` - Hide all output for this test case while the contest is active
* `hide_ignore_active` - Hide input/output (depending on if they are already set) regardless of if the contest is active

These are specified by comma separating:
```
|hide_input,hide_output,hide_ignore_active|hidden
|hide_input,hide_output|hidden only when active
|hide_output|not hidden
|hide_input|hidden only when active
not hidden
```

2022-03-31 16:32 UTC, Brikaa requested changes

2022-03-31 16:32 UTC, Brikaa commented on platform/api/controllers/ContestsController.js
> +        let test_cases = get_case(contest)
```suggestion
        let test_cases = get_cases(contest)
```

2022-03-31 16:56 UTC, Brikaa reviewed
The solutions re-validation do not work because `check_submission_validity` parameters need to change in the re-validate submissions action.

2022-03-31 20:57 UTC, Brikaa requested changes

2022-03-31 20:57 UTC, Brikaa commented on platform/api/controllers/admin/ContestsController.js
> +        let test_cases = get_cases(contest)
This is another controller so `get_cases()` can't be used. We can have `get_cases()` in `platform/api/services/contests.js`

2022-03-31 21:13 UTC, HexF commented on platform/api/controllers/admin/ContestsController.js
> +        let test_cases = get_cases(contest)
Does sails support importing from other files?

2022-03-31 21:19 UTC, realtux commented on platform/api/controllers/admin/ContestsController.js
> +        let test_cases = get_cases(contest)
files in the services folder are exposed globally by their filename minus the .js

2022-04-01 08:47 UTC, HexF commented
Tested it now, and its working. Should be ready to merge:
![image](https://user-images.githubusercontent.com/11236933/161228737-99fa9289-a2b2-4c4e-b629-63396ab1fcca.png)
![image](https://user-images.githubusercontent.com/11236933/161228777-04e6bd53-83ea-42bc-8780-92f41d7427dc.png)
![image](https://user-images.githubusercontent.com/11236933/161228829-7b1b5638-688b-4807-8a95-79f75295d7ca.png)
![image](https://user-images.githubusercontent.com/11236933/161228678-bb18b1fe-9528-4559-bdcf-c3ad4b2cb8b2.png)

2022-04-01 16:41 UTC, merged